# Generated by Django 3.1.4 on 2021-01-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210124_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorite_users',
        ),
    ]
